app/profile/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField,StringField,SubmitField
from wtforms.validators import Required

class UpdateProfileForm(FlaskForm):
    """This defines the properties of the profile form

    Args:
        FlaskForm ([type]): [description]
    """
    bio = TextAreaField('Tell us a bit about yourself',validators=[Required()])
    mobile = StringField('Enter your mobile number...',validators=[Required()])
    submit = SubmitField('Submit')

app/profile/__init__.py
from flask import Blueprint

profile = Blueprint('profile',__name__,url_prefix='/profile')

from . import views,forms

app/profile/views.py
from flask_login.utils import login_required
from flask import render_template,request,redirect,url_for,abort

from . import profile
from app.models import User,Blog
from app import photos,db
from .forms import UpdateProfileForm

@profile.route('/<username>',methods=["GET","POST"])
@login_required
def profile_index(username):
    """This defines the contents of the profile page

    Args:
        username ([type]): [description]
    """
    user = User.query.filter_by(username = username).first()
    blogs = Blog.query.filter_by(author_id = user.id).all()

    return render_template('profile/profile.html',user = user,blogs = blogs)

@profile.route('/<username>/update_pic',methods= ['POST'])
@login_required
def update_pic(username):
    """This is responsible for updating the user profile pic

    Args:
        username ([type]): [description]

    Returns:
        [type]: [description]
    """
    user = User.query.filter_by(username = username).first()
    if user is None:
        abort(404)

    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('profile.profile_index',username = username))

@profile.route('/<username>/update_profile',methods = ["POST","GET"])
@login_required
def update_profile(username):
    """This is responsible for updating the user profile

    Args:
        username ([type]): [description]
    """
    user = User.query.filter_by(username = username).first()

    if user is None:
        abort(404)
    else:
    

        form = UpdateProfileForm()

        if form.validate_on_submit():
            user.bio = form.bio.data
            user.mobile = form.mobile.data

            db.session.add(user)
            db.session.commit()

            return redirect(url_for('profile.profile_index',username = user.username))

        return render_template('profile/update_profile.html',form = form)

app/templates/profile/profile.html
{% extends 'base.html' %}{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-5">
            {% if user.profile_pic_path %}
            <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail"> {% else %}
            <form action="{{url_for('profile.update_pic',username=user.username)}}" method="post" enctype="multipart/form-data">
                <input type="file" name="photo" class="form-control" required>
                <input type="submit">
            </form>
            {% endif %}
        </div>
        <div class="col-md-5" method="POST">
            <div class="mb-3">
                <p>Name: {{ user.username }}</p>
            </div>
            <div class="mb-3">
                {% if user.bio %}
                <p>Bio: {{ user.bio }}</p>
                {% else %}
                <p>No bio, <a href="{{ url_for('profile.update_profile',username = user.username)}}">add bio?</a> {% endif %}
            </div>
            <h2>Contact Information</h2>
            <div class="mb-3">
                <p>Email: {{ user.email }}</p>
            </div>
            <div class="mb-3">
                {% if user.mobile %}
                <p>Mobile Number: {{ user.mobile }}</p>
                {% else %}
                <p>There is no saved mobile number,<a href="{{ url_for('profile.update_profile',username = user.username)}}">add one?</a></p>
                {% endif %}
            </div>
        </div>
        <div class="col-md-1"></div>
    </div>
    <div class="row">
        <div class="col-md-5">
            <h2><u>Blogs</u></h2>
            {% for blog in blogs %}
            <div class="card" style="margin: 10px;">
                <h5 class="card-header">{{ blog.title }}</h5>
                <div class="card-body">
                    <h5 class="card-title">{{ blog.meta_title}}</h5>
                    <p class="card-text">{{ blog.body|truncate(20)|safe }}</p>
                    <a href="{{ url_for('blog.show_blog',title = blog.title)}}" class="btn btn-secondary">See Blog</a>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="col-md-1"></div>
        <div class="col-md-5">
            <h2><u>Contributions</u></h2>
        </div>
        <div class="col-md-1"></div>
    </div>
</div>
{% endblock %}

app/templates/profile/update_profile.html
{% extends 'base.html' %}{% block content %}
<div class="container-fluid">
    <form class="container" method="POST">
        {{ form.hidden_tag()}}
        <div class="mb-3">
            {{ form.bio.label(class="form.label")}}{{ form.bio(class="form-control")}}
        </div>
        <div class="mb-3">
            {{ form.mobile.label(class="form.label")}}{{ form.mobile(class="form-control")}}
        </div>
        {{ form.submit(class="btn btn-success")}}
    </form>
</div>
{% endblock %}