app/blog/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField,StringField,SubmitField,RadioField
from wtforms.validators import Required

class BlogForm(FlaskForm):
    """This defines all the data to be collected from a user for the blog

    Args:
        FlaskForm ([type]): [description]
    """

    title = StringField('Enter the title of the blog',validators=[Required()])
    meta_title = StringField('Enter a brief summary of the blog',validators=[Required()])
    blog = TextAreaField('Enter the blog itself')
    category = RadioField('Enter the category in which your blog falls',validators=[Required()],choices=[('technology'),('finance'),('religion'),('fashion'),('food'),('music'),('lifestyle'),('sports'),('travel'),('politics'),('movie'),('gaming'),('cars')])
    submit = SubmitField('Create Blog')

class CommentForm(FlaskForm):
    """This defines the data to be collected from the comment form

    Args:
        FlaskForm ([type]): [description]
    """
    comment = StringField('Enter your comment below',validators=[Required()])
    submit = SubmitField('Submit')

app/blog/__init__.py
from flask import Blueprint

blog = Blueprint('blog',__name__,url_prefix='/blog')

from . import views,forms

app/blog/views.py
from flask_login.utils import login_required
from flask_login import current_user
from flask import redirect,url_for,flash,render_template

from app.models import Blog,Category,Comment
from . import blog
from .forms import BlogForm, CommentForm
from app import db
from app.models import User,Subscriber
from app.email import new_blog_message

@blog.route('/create_blog',methods = ['POST','GET'])
@login_required
def create_blog():
    """This defines the creation of a new form
    """
    form = BlogForm()

    if form.validate_on_submit():
        blog = Blog(title = form.title.data,meta_title = form.title.data,body = form.blog.data,author_id = current_user.id)
        db.session.add(blog)
        category = Category.query.filter_by(category_name = form.category.data).first()
        category.category.append(blog)

        db.session.commit()
        emails = Subscriber.query.add_columns(Subscriber.email).all()
        for email in emails:
            user = Subscriber.query.filter_by(email = email.email).first()
            new_blog_message("New BLOG","email/new_blog",email.email,user = user,blog = blog)

        flash("Blog Created")
        return redirect(url_for('blog.show_blogs'))

    return render_template('blog/create_blog.html',form = form)

@blog.route('/blogs')
def show_blogs():
    blogs = Blog.query.order_by(Blog.posted.desc()).limit(4)

    return render_template('blog/blogs.html',blogs = blogs)

@blog.route('/<title>',methods=['POST','GET'])
def show_blog(title):
    """This will render a single blog
    """
    form = CommentForm()
    blog = Blog.query.filter_by(title = title).first()
    comments = blog.comment

    if form.validate_on_submit():
        comment = Comment(comment_body = form.comment.data,author_id = current_user.id,blog_id = blog.id)
        db.session.add(comment)
        db.session.commit()

        return redirect(url_for('blog.show_blog',title = title))

    return render_template('blog/blog.html',blog = blog,form = form,comments = comments)

@blog.route('/<id>/<title>')
@login_required
def delete_comment(id,title):
    """This deletes the comment
    """
    comment = Comment.query.filter_by(id = id).first()
    db.session.delete(comment)
    db.session.commit()

    return redirect(url_for('blog.show_blog',title = title))

@blog.route('/blogs/delete/<title>')
@login_required
def delete_blog(title):
    """This deletes a blog
    """
    blog = Blog.query.filter_by(title = title).first()

    db.session.delete(blog)
    db.session.commit()

    return redirect(url_for('blog.show_blogs'))

@blog.route('/<title>/update_blog',methods = ['POST','GET'])
@login_required
def update_blog(title):
    """This defines the creation of a new form
    """
    blog = Blog.query.filter_by(title = title).first()
    form = BlogForm()

    if form.validate_on_submit():
        blog.title = form.title.data
        blog.meta_title = form.meta_title.data
        blog.body = form.blog.data
        blog.author_id = current_user.id
        db.session.add(blog)
        category = Category.query.filter_by(category_name = form.category.data).first()
        category.category.append(blog)

        db.session.commit()

        flash("Blog Updated")
        return redirect(url_for('blog.show_blogs'))

    return render_template('blog/update_blog.html',form = form)

app/templates/blog/blog.html
{% extends 'base.html' %}{% block content %}
<div class="container-fluid" style="text-align: left;display: flex;justify-content: center;">
    <div class="" style="border-left: black solid 2px;border-right: black solid 2px;width: fit-content;height: 100vh; position: relative; padding: 10px;padding-top: 100px;">
        <div class="mb-3" style="text-align: center;">
            <h1><u>{{ blog.title}}</u></h1>
        </div>
        <p>{{ blog.body|safe }}</p>
        <div style="position: absolute; top:10px;right: 10px;">
            <span class="badge rounded-pill bg-dark">{{ blog.posted.strftime('%Y-%m-%d') }}</span>
        </div>
        <div style="position: absolute; top:10px;left: 10px;">
            <span class="badge rounded-pill bg-dark">{{ blog.category[0].category_name }}</span>
        </div>
        {% if current_user.id == blog.author.id %}
        <div style="position: absolute; top:40px;left: 10px;">
            <a href="{{ url_for('blog.update_blog',title = blog.title)}}" class="btn btn-secondary">Update Blog</a>
        </div>
        {% endif %}
        <div class="accordion" id="accordionExample">
            <div class="accordion-item">
                <h2 class="accordion-header" id="headingOne">
                    <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">Comment</button>
                </h2>
                <div id="collapseOne" class="accordion-collapse collapse " aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                        <form method="POST">
                            {{ form.hidden_tag()}}
                            <div class="mb-3">
                                {{form.comment.label(class="form-label")}}{{ form.comment(class="form-control")}}
                            </div>
                            {{ form.submit(class="btn btn-success")}}
                        </form>
                        <hr>
                        <div>
                            <h3><u>Comments</u></h3>
                            {% for comment in comments %}
                            <div class="card" style="margin:10px">
                                <div class="card-body">
                                    <p class="card-text">{{ comment.comment_body }}</p>
                                    <p class="card-text"><small class="text-muted">{{ comment.author.username }}</small></p>
                                    {% if current_user.id == blog.author.id %}
                                    <a href="{{ url_for('blog.delete_comment',title = blog.title,id = comment.id)}}" class="btn btn-danger">Remove</a> {% endif %}
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/blog/blogs.html
{% extends 'base.html'%}{% block content %}
<div class="container">
    {% for blog in blogs %}
    <div class="card" style="margin: 10px;">
        <div class="card-body">
            <h5 class="card-title">{{ blog.title }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{{ blog.meta_title }}</h6>
            <p class="card-text">{{ blog.author.username }}</p>
            <p class="card-text">{{ blog.posted.strftime('%Y-%m-%d') }}</p>
            <a href="{{ url_for('blog.show_blog',title = blog.title)}}" class="btn btn-secondary">See blog</a> {% if current_user.id == blog.author.id %}
            <a href="{{url_for('blog.delete_blog',title = blog.title)}}" class="btn btn-danger">Delete Blog</a> {% endif %}
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

app/templates/blog/create_blog.html
{% extends 'base.html'%} {% block content %}
<link href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

<!-- include summernote css/js -->
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
<div class="create_blog">
    <form class="container-fluid" method="POST">
        {{ form.hidden_tag()}}
        <div class="mb-3">
            {{ form.title.label(class="form-label")}}{{form.title(class="form-control")}}
        </div>
        <div class="mb-3">
            {{ form.meta_title.label(class="form-label")}}{{form.meta_title(class="form-control")}}
        </div>
        <div class="mb-3">
            {{ form.blog.label(class="form-label")}}{{ form.blog(id="editor")}}
        </div>
        <div class="mb-3">
            {{ form.category.label(class="form-label")}}{{form.category(class="list-check-input")}}
        </div>
        {{ form.submit(class="btn btn-secondary")}}
    </form>
    <script>
        $(document).ready(function() {
            $('#editor').summernote();
        });
    </script>
</div>{% endblock %}

app/templates/blog/update_blog.html
{% extends 'base.html'%}{% block content %}
<link href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

<!-- include summernote css/js -->
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
<div class="create_blog">
    <form class="container-fluid" method="POST">
        {{ form.hidden_tag()}}
        <div class="mb-3">
            {{ form.title.label(class="form-label")}}{{form.title(class="form-control")}}
        </div>
        <div class="mb-3">
            {{ form.meta_title.label(class="form-label")}}{{form.meta_title(class="form-control")}}
        </div>
        <div class="mb-3">
            {{ form.blog.label(class="form-label")}}{{ form.blog(id="editor")}}
        </div>
        <div class="mb-3">
            {{ form.category.label(class="form-label")}}{{form.category(class="list-group-flush")}}
        </div>
        {{ form.submit(class="btn btn-secondary")}}
    </form>
    <script>
        $(document).ready(function() {
            $('#editor').summernote();
        });
    </script>
</div>{% endblock %}